const trans = {
    'ko': {
        ok: '확인',
        cancel: '취소',
        apply: '적용',
        init: '초기화',
        start: '시작',
        detectStart: '감지시작',
        stop: '정지',
        name: '이름 변경',
        sens: '민감도 변경',
        loginSuccess: ['로그인 성공', '환영합니다! ', '님'],
        loginFail: ['로그인 실패', '로그인에 실패하였습니다.'],
        menu: ['가이드', '텍스트 설정', '소리 설정', '설정'],
        guide: ['Sound Alarm은 미리 등록한 소리와 단어를 마이크를 통해 감지를 해서 알림을 보내주는 서비스입니다.',
                '텍스트 등록 방법',
                '감지되길 원하는 단어를 한글로 입력하고 추가버튼을 눌러 등록합니다.',
                '(숫자나 영어는 인식이 불가능합니다.)',
                '사운드 등록 방법',
                '1. 원하는 사운드를 스마트폰등을 이용하여 녹음을 합니다.',
                '(인식 정확도를 높이기 위해서는 최대한 잡음 없이 녹음이 되어야 합니다.)',
                '2. 녹음된 파일을 "파일 업로드" 버튼을 눌러서 선택합니다.',
                '3. "파일 업로드" 오른쪽에 있는 입력창을 통해 등록하고자 하는 이름으로 변경을 하신 뒤 추가버튼을 누릅니다.',
                '4. 마이크가 최대한 밖의 소리를 수음할 수 있도록 세팅한 뒤 민감도 설정의 녹음버튼을 누릅니다.',
                '(설정탭의 마이크 테스트를 통해서 소리가 정상적으로 수음되는지 확인할 수 있습니다.)',
                '5. 3초이상 녹음한 뒤 정지버튼을 누릅니다. (일반적인 환경에서의 점수를 측정하는 과정입니다.)',
                '6. 측정된 현재 점수로 민감도를 조정합니다.',
                '7. 녹음된 파일을 재생할 준비를 한 뒤 녹음 버튼을 다시 누릅니다.',
                '8. 녹음된 파일을 최대한 들리는 것과 유사한 볼륨으로 3초이상 녹음한 뒤 정지버튼을 누릅니다.',
                '9. 측정된 현재 점수와 기존의 민감도 점수 사이의 적당한 값을 지정합니다.',
                '10. 민감도 설정을 완료한 후, 감지를 시작한 뒤 녹음된 파일을 재생해보면서 적당한 민감도를 설정해줍니다.'],
        text: ['새로운 텍스트를 추가해 주세요!', '이름을 입력해 주세요', '텍스트는 최대 10개까지 등록할 수 있습니다', '텍스트는 한글만 인식할 수 있습니다.'],
        sound: ['새로운 소리 파일을 추가해 주세요!', '파일 업로드', '이름을 입력해 주세요', '파일은 최대 5개까지 등록할 수 있습니다.', 
                '파일 하나의 최대 용량은 300KB 입니다.'],
        setting: ['알림 소리 설정', '알림 푸쉬 설정', '마이크 테스트', '로그아웃', '벨소리 설정', '알람 1', '알람 2', '알람 3'],
        sensitivity: ['민감도', '의 민감도 설정', '현재 점수', '측정 전 입니다.', '민감도 설정', 
                      '녹음 버튼을 클릭하여 현재 마이크를 통해 소리를 5초 이상 입력하고 녹음을 종료합니다.',
                      '민감도를 높일수록 소리의 구분이 정확해지지만 인식되는 빈도가 낮아질 수 있습니다.', 
                      '만약 출력되는 점수가 60 이하가 반복된다면, 녹음 파일이나 현재 기기를 조정할 것을 추천드립니다.'],
        uploadFail: ['업로드 실패', '같은 이름으로 등록할 수 없습니다!', '', '최대 10개의 문자만 등록할 수 있습니다!', '파일의 용량이 큽니다! 300kb 이하의 파일을 업로드하세요!', 
                    '최대 5개의 파일만 등록할 수 있습니다!', ],
        delete: ['삭제하시겠습니까?', '을(를) 정말로 삭제하시겠습니까?,', '삭제'],
        logout: ['로그아웃 성공', '로그아웃에 성공하였습니다'],
        detecting: ['감지 중입니다.', '이(가) 감지 되었습니다!', '음성 목록', '텍스트 목록'],
        push: ["이(가) 감지되었습니다!!", "감지되었습니다!"],
    },
    'en': {
        ok: 'OK',
        cancel: 'Cancel',
        apply: 'Apply',
        init: 'Initialize',
        start: 'Start',
        detectStart: 'Start',
        stop: 'Stop',
        name: 'Rename',
        sens: 'Modify Sensitivity',
        loginSuccess: ['Login Successful', 'Welcome! ', ''],
        loginFail: ['Login Failed', 'Login Faiiled'],
        menu: ['Guide', 'Text', 'Sound', 'Setting'],
        guide: ['Sound Alarm is a service that detects pre-registered sounds and words through a microphone and sends notifications.',
                'To register text',
                'Type the word you want to be detected in English and press the Add button to register.',
                '(Only English can be recognized.)',
                'To register a sound',
                '1. Record the sound you want.',
                '(In order to increase the recognition accuracy, it is necessary to record as noise-free as possible.)',
                '2. Tap the "Upload File" button to select the recorded file.',
                '3. Use the input window to the right of "Upload File" to change the name you want to register, and then click the Add button.',
                '4. Set the microphone to receive as many sounds as possible, then press the Record button in Sensitivity Settings.',
                '5. Record for at least 3 seconds and press the Stop button. (The process of measuring scores in a typical environment.)',
                '6. Adjust sensitivity with the current measured score.',
                '7. Prepare to play the recorded file and press the record button again.',
                '8. Play the recorded file to a volume as similar as it sounds, record it for at least 3 seconds, and then press the Stop button.',
                '9. Sets the appropriate value between the current score and the existing sensitivity score.',
                '10. After completing the sensitivity setting, start detecting and play the recorded file to set the appropriate sensitivity.'],
        text: ['Please add new text!', 'Please enter the name', 'You can register up to 10 words.', 'Only English words can be recognized.'],
        sound: ['Please add new sound files!', 'Upload file', 'Please enter the name', 'You can upload up to 5 files.', 
                'The maximum capacity of a single file is 300 KB.'],
        setting: ['Alarm sound', 'Alarm push', 'Microphone test', 'Logout', 'Ring Tone', 'Alarm 1', 'Alarm 2', 'Alarm 3'],
        sensitivity: ['Sensitivity', '\'s sensitivity', 'Current score', 'Before the measurement', 'Sensitivity', 
                      'Click the Record button to enter the sound through the current microphone for at least 5s and exit the recording.',
                      'The higher the sensitivity, the more accurate the classification of sounds, but the frequency of recognition may decrease', 
                      'If the printed score is repeated below 60, we recommend adjusting the recording file or current device.'],
        uploadFail: ['Upload failed', 'Unable to register with the same name!', '', 'You can register up to 10 words.',
                     'The file has a large capacity! Upload files below 300kb!', 
                    'You can upload up to 5 files.', ],
        delete: ['Delete?', 'Are you sure you want to delete ', 'Delete'],
        logout: ['Logout Successful', 'Logout Successful!'],
        detecting: ['Detecting..', 'is detected!', 'Sound List', 'Text List'],
        push: ["is detected!!", "Detected!!"],
    },
};

export default trans;